name: docker-image

on:
  workflow_dispatch:
  push:
    branches:
      - ecx-*
  pull_request:
    branches:
      - ecx-*

env:
  IMAGE_ORGANIZATION: ${{ secrets.DOCKERHUB_USERNAME }}
  IMAGE_NAME: promtail

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/arm64,linux/amd64
          version: v0.9.1

      - name: Get image tags
        id: image_tags
        run: |
          echo -n ::set-output name=IMAGE_TAGS::
          PULLSPEC="$IMAGE_ORGANIZATION/$IMAGE_NAME"
          TAGS=("$PULLSPEC:axe-agent",)
          BUILD_DATE="$(date -u +'%Y-%m-%d')"
          VCS_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          VCS_REF="$(git rev-parse --short HEAD)"
          TAGS+=("$PULLSPEC:$VCS_BRANCH-$BUILD_DATE-$VCS_REF")
          ( IFS=$','; echo "${TAGS[*]}" )

      - name: Build and publish image on quay.io
        uses: docker/build-push-action@v2
        with:
          context: .
          file: clients/cmd/promtail/Dockerfile
          push: true
          tags: "${{ steps.image_tags.outputs.IMAGE_TAGS }}"
          platforms: linux/arm64,linux/amd64